project_name: ggen
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: ggen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/Nabby12/ggen/cmd/handlers/version.Version={{ .Version }}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - tap:
      owner: Nabby12
      name: homebrew-ggen
      token: "{{ .Env.ACCESS_TOKEN }}"
    folder: Formula
    homepage: 'https://github.com/Nabby12/ggen'
    description: 'ggen is a simple CLI tool via Golang.'
    license: 'MIT'
